In [32]:
import pandas as pd

In [34]:
dataset = pd.read_csv(r"C:\Users\conte\Downloads\archive (8)\placement.csv")

In [35]:
dataset.head(5)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [36]:
x = dataset[["cgpa"]]
y = dataset["package"]

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42)

In [39]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [46]:
lr = LinearRegression()
lr.fit(x_train,y_train)
lr.score(x_train,y_train)*100 , lr.score(x_test,y_test)*100

(77.48832241653935, 77.74721122516276)

In [47]:
sv = SVR()
sv.fit(x_train,y_train)
sv.score(x_train,y_train)*100 , lr.score(x_test,y_test)*100

(78.16541869605287, 77.74721122516276)

In [48]:
dt = DecisionTreeRegressor()
dt.fit(x_train,y_train)
dt.score(x_train,y_train)*100 , lr.score(x_test,y_test)*100

(94.91076608952679, 77.74721122516276)

In [49]:
from sklearn.ensemble import VotingRegressor

In [51]:
li = [("lr1",LinearRegression()),("dt1",DecisionTreeRegressor()),("sv1",SVR())]

In [52]:
vc = VotingRegressor(li)
vc.fit(x_train,y_train)

VotingRegressor(estimators=[('lr1', LinearRegression()),
                            ('dt1', DecisionTreeRegressor()), ('sv1', SVR())])

In [53]:
vc.score(x_train,y_train)*100,  vc.score(x_train,y_train)*100

(87.42675418325024, 87.42675418325024)

In [54]:
df = {"lr":lr.predict(x_test),"svm":sv.predict(x_test),"dt":dt.predict(x_test),"vc":vc.predict(x_test)}

In [56]:
pd.DataFrame(df).head(5)

         lr       svm      dt        vc
0  2.786588  2.735463  2.9200  2.814017
1  3.140678  3.115500  3.2525  3.169559
2  3.203501  3.197764  2.9200  3.107088
3  2.398231  2.408542  2.5400  2.448924
4  3.529035  3.623576  3.9900  3.714204